[package]
name = "portal-jsc-common"
version = "0.8.0-pre.3"
edition = "2024"
license = "MPL-2.0"
description = "ECMAScript IR"

[dependencies]
either = { version = "^1.15.0", default-features = false }
portal-pc-asm-common = "^0.1.0"
